
create table if not exists ops_panel.goalfy_sync_runs (
  id uuid primary key default gen_random_uuid(),
  board_id text not null,
  mode text not null default 'cards_api',
  status text not null default 'running' check (status in ('running','success','partial','error')),
  total_cards integer,
  processed_cards integer not null default 0,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  error text,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists ops_panel.goalfy_sync_state (
  board_id text primary key,
  mode text not null default 'cards_api',
  status text not null default 'never',
  total_cards integer,
  processed_cards integer not null default 0,
  last_sync_started_at timestamptz,
  last_synced_at timestamptz,
  last_success_at timestamptz,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists ops_panel.goalfy_phases (
  phase_id text primary key,
  board_id text not null,
  phase_name text not null,
  phase_index numeric,
  archived boolean not null default false,
  raw jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now()
);

create table if not exists ops_panel.goalfy_dns (
  card_id text primary key,
  board_id text not null,
  project_core text,
  project_display text,
  dn_number text,
  card_title text,
  phase_id text,
  phase_name text,
  phase_index numeric,
  client text,
  project_manager text,
  destination text,
  dn_for text,
  po_number text,
  items_text text,
  brasfels_items jsonb not null default '[]'::jsonb,
  tags text[] not null default '{}'::text[],
  invoice_number text,
  invoice_url text,
  created_at_source timestamptz,
  updated_at_source timestamptz,
  date_in_current_phase timestamptz,
  finished_at_source timestamptz,
  ready_at timestamptz,
  shipped_at timestamptz,
  is_ready boolean not null default false,
  is_shipped boolean not null default false,
  is_active boolean not null default true,
  material_scope text not null default 'unknown'
    check (material_scope in ('spool','loose','mixed','other','unknown')),
  sync_run_id uuid references ops_panel.goalfy_sync_runs(id) on delete set null,
  raw jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now()
);

create table if not exists ops_panel.goalfy_dn_items (
  id bigint generated by default as identity primary key,
  card_id text not null references ops_panel.goalfy_dns(card_id) on delete cascade,
  project_core text,
  item_key text not null,
  item_label text,
  relation_id text,
  item_type text,
  quantity numeric,
  source_field text not null default 'unknown',
  raw jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now(),
  unique(card_id,item_key,source_field)
);

create table if not exists ops_panel.goalfy_dn_phase_history (
  id bigint generated by default as identity primary key,
  card_id text not null references ops_panel.goalfy_dns(card_id) on delete cascade,
  phase_id text,
  phase_name text not null,
  phase_order numeric,
  entered_at timestamptz,
  exited_at timestamptz,
  duration_minutes numeric,
  raw jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now()
);

create index if not exists goalfy_dns_project_idx on ops_panel.goalfy_dns(project_core) where is_active;
create index if not exists goalfy_dns_phase_idx on ops_panel.goalfy_dns(phase_name) where is_active;
create index if not exists goalfy_dns_shipped_idx on ops_panel.goalfy_dns(project_core,is_shipped) where is_active;
create index if not exists goalfy_dn_items_project_idx on ops_panel.goalfy_dn_items(project_core,item_key);
create index if not exists goalfy_dn_items_card_idx on ops_panel.goalfy_dn_items(card_id);
create index if not exists goalfy_dn_history_card_idx on ops_panel.goalfy_dn_phase_history(card_id,entered_at);

alter table ops_panel.goalfy_sync_runs enable row level security;
alter table ops_panel.goalfy_sync_state enable row level security;
alter table ops_panel.goalfy_phases enable row level security;
alter table ops_panel.goalfy_dns enable row level security;
alter table ops_panel.goalfy_dn_items enable row level security;
alter table ops_panel.goalfy_dn_phase_history enable row level security;

revoke all on ops_panel.goalfy_sync_runs from anon,authenticated;
revoke all on ops_panel.goalfy_sync_state from anon,authenticated;
revoke all on ops_panel.goalfy_phases from anon,authenticated;
revoke all on ops_panel.goalfy_dns from anon,authenticated;
revoke all on ops_panel.goalfy_dn_items from anon,authenticated;
revoke all on ops_panel.goalfy_dn_phase_history from anon,authenticated;

grant all on ops_panel.goalfy_sync_runs to service_role;
grant all on ops_panel.goalfy_sync_state to service_role;
grant all on ops_panel.goalfy_phases to service_role;
grant all on ops_panel.goalfy_dns to service_role;
grant all on ops_panel.goalfy_dn_items to service_role;
grant all on ops_panel.goalfy_dn_phase_history to service_role;
grant usage,select on all sequences in schema ops_panel to service_role;

create or replace function public.ops_goalfy_begin_sync(
  p_board_id text,
  p_mode text default 'cards_api',
  p_total_cards integer default null,
  p_metadata jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path=public,ops_panel
as $$
declare
  v_id uuid;
begin
  insert into ops_panel.goalfy_sync_runs(board_id,mode,status,total_cards,metadata)
  values(p_board_id,coalesce(nullif(p_mode,''),'cards_api'),'running',p_total_cards,coalesce(p_metadata,'{}'::jsonb))
  returning id into v_id;

  insert into ops_panel.goalfy_sync_state(
    board_id,mode,status,total_cards,processed_cards,last_sync_started_at,last_error,metadata,updated_at
  )
  values(
    p_board_id,coalesce(nullif(p_mode,''),'cards_api'),'running',p_total_cards,0,now(),null,
    coalesce(p_metadata,'{}'::jsonb),now()
  )
  on conflict(board_id) do update
  set mode=excluded.mode,
      status='running',
      total_cards=excluded.total_cards,
      processed_cards=0,
      last_sync_started_at=now(),
      last_error=null,
      metadata=ops_panel.goalfy_sync_state.metadata||excluded.metadata,
      updated_at=now();

  return v_id;
end $$;

create or replace function public.ops_goalfy_ingest_phases(
  p_board_id text,
  p_phases jsonb
)
returns integer
language plpgsql
security definer
set search_path=public,ops_panel
as $$
declare
  v_count integer:=0;
begin
  insert into ops_panel.goalfy_phases(phase_id,board_id,phase_name,phase_index,archived,raw,synced_at)
  select
    x->>'id',
    p_board_id,
    coalesce(nullif(x->>'title',''),nullif(x->>'name',''),'Fase'),
    nullif(x->>'index','')::numeric,
    coalesce((x->>'archived')::boolean,false),
    x,
    now()
  from jsonb_array_elements(coalesce(p_phases,'[]'::jsonb)) x
  where nullif(x->>'id','') is not null
  on conflict(phase_id) do update
  set board_id=excluded.board_id,
      phase_name=excluded.phase_name,
      phase_index=excluded.phase_index,
      archived=excluded.archived,
      raw=excluded.raw,
      synced_at=now();

  get diagnostics v_count=row_count;
  return v_count;
end $$;

create or replace function public.ops_goalfy_ingest_cards(
  p_run_id uuid,
  p_cards jsonb
)
returns integer
language plpgsql
security definer
set search_path=public,ops_panel,ops_core
as $$
declare
  v_card jsonb;
  v_card_id text;
  v_project_core text;
  v_count integer:=0;
  v_item jsonb;
  v_hist jsonb;
begin
  for v_card in select value from jsonb_array_elements(coalesce(p_cards,'[]'::jsonb))
  loop
    v_card_id:=nullif(v_card->>'card_id','');
    if v_card_id is null then
      continue;
    end if;

    v_project_core:=ops_core.normalize_project_core(coalesce(v_card->>'project_core',v_card->>'project_display'));

    insert into ops_panel.goalfy_dns(
      card_id,board_id,project_core,project_display,dn_number,card_title,
      phase_id,phase_name,phase_index,client,project_manager,destination,dn_for,po_number,
      items_text,brasfels_items,tags,invoice_number,invoice_url,
      created_at_source,updated_at_source,date_in_current_phase,finished_at_source,
      ready_at,shipped_at,is_ready,is_shipped,is_active,material_scope,
      sync_run_id,raw,synced_at
    )
    values(
      v_card_id,
      coalesce(v_card->>'board_id',''),
      v_project_core,
      nullif(v_card->>'project_display',''),
      nullif(v_card->>'dn_number',''),
      nullif(v_card->>'card_title',''),
      nullif(v_card->>'phase_id',''),
      nullif(v_card->>'phase_name',''),
      nullif(v_card->>'phase_index','')::numeric,
      nullif(v_card->>'client',''),
      nullif(v_card->>'project_manager',''),
      nullif(v_card->>'destination',''),
      nullif(v_card->>'dn_for',''),
      nullif(v_card->>'po_number',''),
      nullif(v_card->>'items_text',''),
      coalesce(v_card->'brasfels_items','[]'::jsonb),
      coalesce(array(select jsonb_array_elements_text(coalesce(v_card->'tags','[]'::jsonb))),'{}'::text[]),
      nullif(v_card->>'invoice_number',''),
      nullif(v_card->>'invoice_url',''),
      nullif(v_card->>'created_at_source','')::timestamptz,
      nullif(v_card->>'updated_at_source','')::timestamptz,
      nullif(v_card->>'date_in_current_phase','')::timestamptz,
      nullif(v_card->>'finished_at_source','')::timestamptz,
      nullif(v_card->>'ready_at','')::timestamptz,
      nullif(v_card->>'shipped_at','')::timestamptz,
      coalesce((v_card->>'is_ready')::boolean,false),
      coalesce((v_card->>'is_shipped')::boolean,false),
      true,
      case
        when v_card->>'material_scope' in ('spool','loose','mixed','other','unknown') then v_card->>'material_scope'
        else 'unknown'
      end,
      p_run_id,
      coalesce(v_card->'raw',v_card),
      now()
    )
    on conflict(card_id) do update
    set board_id=excluded.board_id,
        project_core=excluded.project_core,
        project_display=excluded.project_display,
        dn_number=excluded.dn_number,
        card_title=excluded.card_title,
        phase_id=excluded.phase_id,
        phase_name=excluded.phase_name,
        phase_index=excluded.phase_index,
        client=excluded.client,
        project_manager=excluded.project_manager,
        destination=excluded.destination,
        dn_for=excluded.dn_for,
        po_number=excluded.po_number,
        items_text=excluded.items_text,
        brasfels_items=excluded.brasfels_items,
        tags=excluded.tags,
        invoice_number=excluded.invoice_number,
        invoice_url=excluded.invoice_url,
        created_at_source=excluded.created_at_source,
        updated_at_source=excluded.updated_at_source,
        date_in_current_phase=excluded.date_in_current_phase,
        finished_at_source=excluded.finished_at_source,
        ready_at=excluded.ready_at,
        shipped_at=excluded.shipped_at,
        is_ready=excluded.is_ready,
        is_shipped=excluded.is_shipped,
        is_active=true,
        material_scope=excluded.material_scope,
        sync_run_id=excluded.sync_run_id,
        raw=excluded.raw,
        synced_at=now();

    delete from ops_panel.goalfy_dn_items where card_id=v_card_id;
    for v_item in select value from jsonb_array_elements(coalesce(v_card->'items','[]'::jsonb))
    loop
      if nullif(v_item->>'item_key','') is null then
        continue;
      end if;

      insert into ops_panel.goalfy_dn_items(
        card_id,project_core,item_key,item_label,relation_id,item_type,quantity,source_field,raw,synced_at
      )
      values(
        v_card_id,
        v_project_core,
        ops_core.normalize_item_key(v_item->>'item_key'),
        nullif(v_item->>'item_label',''),
        nullif(v_item->>'relation_id',''),
        nullif(v_item->>'item_type',''),
        nullif(v_item->>'quantity','')::numeric,
        coalesce(nullif(v_item->>'source_field',''),'unknown'),
        v_item,
        now()
      )
      on conflict(card_id,item_key,source_field) do update
      set project_core=excluded.project_core,
          item_label=excluded.item_label,
          relation_id=excluded.relation_id,
          item_type=excluded.item_type,
          quantity=excluded.quantity,
          raw=excluded.raw,
          synced_at=now();
    end loop;

    delete from ops_panel.goalfy_dn_phase_history where card_id=v_card_id;
    for v_hist in select value from jsonb_array_elements(coalesce(v_card->'phase_history','[]'::jsonb))
    loop
      if nullif(v_hist->>'phase_name','') is null then
        continue;
      end if;

      insert into ops_panel.goalfy_dn_phase_history(
        card_id,phase_id,phase_name,phase_order,entered_at,exited_at,duration_minutes,raw,synced_at
      )
      values(
        v_card_id,
        nullif(v_hist->>'phase_id',''),
        v_hist->>'phase_name',
        nullif(v_hist->>'phase_order','')::numeric,
        nullif(v_hist->>'entered_at','')::timestamptz,
        nullif(v_hist->>'exited_at','')::timestamptz,
        nullif(v_hist->>'duration_minutes','')::numeric,
        v_hist,
        now()
      );
    end loop;

    v_count:=v_count+1;
  end loop;

  update ops_panel.goalfy_sync_runs
  set processed_cards=processed_cards+v_count
  where id=p_run_id;

  update ops_panel.goalfy_sync_state s
  set processed_cards=r.processed_cards,
      updated_at=now()
  from ops_panel.goalfy_sync_runs r
  where r.id=p_run_id and s.board_id=r.board_id;

  return v_count;
end $$;

create or replace function public.ops_goalfy_finish_sync(
  p_run_id uuid,
  p_success boolean,
  p_error text default null,
  p_total_cards integer default null,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=public,ops_panel
as $$
declare
  r ops_panel.goalfy_sync_runs%rowtype;
begin
  select * into r from ops_panel.goalfy_sync_runs where id=p_run_id;
  if not found then raise exception 'Run Goalfy não encontrado.'; end if;

  update ops_panel.goalfy_sync_runs
  set status=case when p_success then 'success' else 'error' end,
      total_cards=coalesce(p_total_cards,total_cards),
      finished_at=now(),
      error=p_error,
      metadata=metadata||coalesce(p_metadata,'{}'::jsonb)
  where id=p_run_id
  returning * into r;

  if p_success then
    update ops_panel.goalfy_dns
    set is_active=false
    where board_id=r.board_id
      and is_active=true
      and sync_run_id is distinct from p_run_id;
  end if;

  insert into ops_panel.goalfy_sync_state(
    board_id,mode,status,total_cards,processed_cards,last_sync_started_at,last_synced_at,last_success_at,last_error,metadata,updated_at
  )
  values(
    r.board_id,r.mode,
    case when p_success then 'success' else 'error' end,
    coalesce(p_total_cards,r.total_cards),r.processed_cards,r.started_at,now(),
    case when p_success then now() else null end,
    p_error,
    r.metadata||coalesce(p_metadata,'{}'::jsonb),
    now()
  )
  on conflict(board_id) do update
  set mode=excluded.mode,
      status=excluded.status,
      total_cards=excluded.total_cards,
      processed_cards=excluded.processed_cards,
      last_sync_started_at=excluded.last_sync_started_at,
      last_synced_at=excluded.last_synced_at,
      last_success_at=coalesce(excluded.last_success_at,ops_panel.goalfy_sync_state.last_success_at),
      last_error=excluded.last_error,
      metadata=ops_panel.goalfy_sync_state.metadata||excluded.metadata,
      updated_at=now();

  return jsonb_build_object(
    'ok',p_success,
    'board_id',r.board_id,
    'processed_cards',r.processed_cards,
    'total_cards',coalesce(p_total_cards,r.total_cards),
    'status',case when p_success then 'success' else 'error' end,
    'error',p_error,
    'finished_at',now()
  );
end $$;

create or replace function public.ops_goalfy_sync_status()
returns jsonb
language sql
stable
security definer
set search_path=public,ops_panel
as $$
select coalesce(
  (
    select to_jsonb(s)
    from ops_panel.goalfy_sync_state s
    order by updated_at desc
    limit 1
  ),
  jsonb_build_object('status','never','processed_cards',0)
);
$$;

create or replace function public.ops_goalfy_project_shipping(p_project_key text)
returns jsonb
language sql
stable
security definer
set search_path=public,ops_panel,ops_core
as $$
with k as (
  select ops_core.normalize_project_core(p_project_key) project_core
),
dns as (
  select d.*
  from ops_panel.goalfy_dns d,k
  where d.project_core=k.project_core and d.is_active
),
expected as (
  select
    i.id,
    i.item_key,
    ops_core.normalize_item_key(coalesce(i.iso_code,i.spool_code,i.drawing_code,i.item_key)) normalized_item_key
  from ops_core.items i
  join ops_core.projects p on p.id=i.project_id
  join k on k.project_core=p.project_core
  where not i.removed_from_scope
    and (
      coalesce(i.source_metadata->>'technical_authority','')='FCB'
      or coalesce(p.source_metadata->>'technical_authority','')='FCB'
         and coalesce(p.source_metadata->>'fcb_status','')='detected'
    )
),
shipped_keys as (
  select distinct gi.item_key
  from ops_panel.goalfy_dn_items gi
  join dns d on d.card_id=gi.card_id
  where d.is_shipped
),
matched as (
  select count(*)::integer matched_expected
  from expected e
  where exists (
    select 1 from shipped_keys s where s.item_key=e.normalized_item_key
  )
),
summary as (
  select
    (select project_core from k) project_core,
    count(*)::integer dn_count,
    count(*) filter(where is_shipped)::integer shipped_dn_count,
    count(*) filter(where is_ready and not is_shipped)::integer ready_dn_count,
    count(*) filter(where not is_shipped)::integer open_dn_count,
    count(distinct material_scope) filter(where material_scope<>'unknown')::integer material_scope_count,
    max(shipped_at) latest_shipped_at,
    max(updated_at_source) latest_goalfy_update,
    (select count(*)::integer from expected) expected_item_count,
    (select count(*)::integer from shipped_keys) shipped_item_count,
    (select matched_expected from matched) matched_expected_item_count
  from dns
),
s as (
  select *,
    case
      when expected_item_count>0
        then round((matched_expected_item_count::numeric/expected_item_count::numeric)*100,1)
      else null
    end coverage_percent,
    case
      when dn_count=0 then 'no_dn'
      when expected_item_count>0 and matched_expected_item_count>=expected_item_count then 'complete'
      when shipped_dn_count>0 and expected_item_count>0 then 'partial'
      when shipped_dn_count>0 and expected_item_count=0 then 'shipping_evidence'
      when ready_dn_count>0 then 'ready'
      else 'processing'
    end shipping_status
  from summary
)
select jsonb_build_object(
  'summary',to_jsonb(s),
  'dns',coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'card_id',d.card_id,
        'dn_number',d.dn_number,
        'card_title',d.card_title,
        'phase_id',d.phase_id,
        'phase_name',d.phase_name,
        'client',d.client,
        'project_manager',d.project_manager,
        'destination',d.destination,
        'dn_for',d.dn_for,
        'po_number',d.po_number,
        'items_text',d.items_text,
        'tags',to_jsonb(d.tags),
        'invoice_number',d.invoice_number,
        'invoice_url',d.invoice_url,
        'date_in_current_phase',d.date_in_current_phase,
        'ready_at',d.ready_at,
        'shipped_at',d.shipped_at,
        'is_ready',d.is_ready,
        'is_shipped',d.is_shipped,
        'material_scope',d.material_scope,
        'updated_at_source',d.updated_at_source,
        'items',coalesce((
          select jsonb_agg(to_jsonb(i) order by i.item_label,i.item_key)
          from ops_panel.goalfy_dn_items i
          where i.card_id=d.card_id
        ),'[]'::jsonb),
        'phase_history',coalesce((
          select jsonb_agg(to_jsonb(h) order by h.entered_at nulls last,h.phase_order nulls last,h.id)
          from ops_panel.goalfy_dn_phase_history h
          where h.card_id=d.card_id
        ),'[]'::jsonb)
      )
      order by coalesce(d.shipped_at,d.updated_at_source,d.synced_at) desc,d.dn_number
    )
    from dns d
  ),'[]'::jsonb),
  'sync',public.ops_goalfy_sync_status()
)
from s;
$$;

grant execute on function public.ops_goalfy_begin_sync(text,text,integer,jsonb) to service_role;
grant execute on function public.ops_goalfy_ingest_phases(text,jsonb) to service_role;
grant execute on function public.ops_goalfy_ingest_cards(uuid,jsonb) to service_role;
grant execute on function public.ops_goalfy_finish_sync(uuid,boolean,text,integer,jsonb) to service_role;
grant execute on function public.ops_goalfy_sync_status() to service_role;
grant execute on function public.ops_goalfy_project_shipping(text) to service_role;
